#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const { appendEvent } = require("./lib/memory-store");

const [file] = process.argv.slice(2);
if (!file) {
  console.error("Usage: node scripts/generate-readme.js runs/<DELIVERY_ID>/workflow-state.json");
  process.exit(1);
}

const statePath = path.resolve(file);
const state = JSON.parse(fs.readFileSync(statePath, "utf8"));
const runDir = path.dirname(statePath);
const deliveryId = state.delivery && state.delivery.id ? state.delivery.id : path.basename(runDir);
const tasks = state.task_graph && Array.isArray(state.task_graph.tasks) ? state.task_graph.tasks : [];
const artifacts = state.artifacts || {};
const contracts = state.contracts && Array.isArray(state.contracts.interfaces) ? state.contracts.interfaces : [];
const gates = state.gates || {};

const feTasks = tasks.filter((t) => ["frontend_dev", "frontend_test"].includes(t.role));
const beTasks = tasks.filter((t) => ["backend_dev", "backend_test"].includes(t.role));
const verified = tasks.filter((t) => t.status === "verified");
const failed = tasks.filter((t) => t.status === "failed");
const blocked = tasks.filter((t) => t.status === "blocked");

const lines = [];
lines.push(`# ${state.delivery && state.delivery.title ? state.delivery.title : deliveryId}`);
lines.push(``);
lines.push(`> **Delivery ID:** ${deliveryId}`);
lines.push(`> **State:** ${state.current_state}`);
lines.push(`> **Updated:** ${state.delivery && state.delivery.updated_at ? state.delivery.updated_at : "n/a"}`);
if (state.delivery && state.delivery.request_summary) {
  lines.push(`> **Summary:** ${state.delivery.request_summary}`);
}
lines.push(``);

lines.push(`## Tasks`);
lines.push(``);
lines.push(`| ID | Title | Role | Status | Dependencies |`);
lines.push(`| --- | --- | --- | --- | --- |`);
for (const task of tasks) {
  const deps = Array.isArray(task.depends_on) && task.depends_on.length ? task.depends_on.join(", ") : "—";
  lines.push(`| ${task.id} | ${task.title || "Untitled"} | ${task.role} | ${task.status} | ${deps} |`);
}
lines.push(``);

lines.push(`## Status Summary`);
lines.push(``);
lines.push(`- **Total tasks:** ${tasks.length}`);
lines.push(`- **Verified:** ${verified.length}`);
lines.push(`- **Failed:** ${failed.length}`);
lines.push(`- **Blocked:** ${blocked.length}`);
lines.push(`- **Frontend tasks:** ${feTasks.length}`);
lines.push(`- **Backend tasks:** ${beTasks.length}`);
lines.push(``);

if (contracts.length) {
  lines.push(`## API Contracts`);
  lines.push(``);
  lines.push(`| ID | Kind | Producer | Consumer | Status |`);
  lines.push(`| --- | --- | --- | --- | --- |`);
  for (const contract of contracts) {
    lines.push(`| ${contract.id} | ${contract.kind} | ${contract.producer_task_id || "—"} | ${contract.consumer_task_id || "—"} | ${contract.status} |`);
  }
  lines.push(``);
}

if (gates.final_review && gates.final_review.status) {
  lines.push(`## Gates`);
  lines.push(``);
  lines.push(`| Gate | Status | Approver |`);
  lines.push(`| --- | --- | --- |`);
  for (const [name, gate] of Object.entries(gates)) {
    lines.push(`| ${name} | ${gate.status || "unknown"} | ${gate.approver || "—"} |`);
  }
  lines.push(``);
}

lines.push(`## Artifacts`);
lines.push(``);
for (const [name, artifact] of Object.entries(artifacts)) {
  if (name === "design_assets") continue;
  lines.push(`- **${name}:** ${artifact.path || "not generated"} (${artifact.status})`);
}
lines.push(``);

lines.push(`---`);
lines.push(`*Generated by agent-spec-ops harness at ${new Date().toISOString()}*`);

const readmePath = path.join(runDir, "README.md");
fs.writeFileSync(readmePath, lines.join("\n") + "\n");
console.log(`Generated: ${readmePath}`);

appendEvent(statePath, {
  type: "artifact_generated",
  role_context: "orchestrator",
  task_id: "",
  target: "README.md",
  summary: `Generated README.md for ${deliveryId}`,
  details: `Wrote ${lines.length} lines to ${readmePath}`,
  severity: "info",
  tags: ["artifact", "readme", deliveryId]
});
